num_joints: 18 #including the hip root joint
fps: 30
dataset_type: FreeManDataset
dataset_name: "freeman"
precomputed_folder: "${dataset_precomputed_path}/FreeMan/${task.task_name}/"
annotations_folder: "${dataset_annotation_path}/FreeMan/${task.task_name}/"
dtype: float32
multimodal_threshold: 0.5

data_loader_valid:
    shuffle: False
    segments_path: "${dataset.annotations_folder}/segments_valid.csv"
    actions: "all"
    drop_last: False
    if_load_mmgt: ${eval:'True if "probabilistic in str(${stats_mode})" else False'}


data_loader_test:
    shuffle: False
    segments_path: "${dataset.annotations_folder}/segments_test.csv"
    actions: "all"
    drop_last: False
    if_load_mmgt: ${eval:'True if "probabilistic" in "${stats_mode}" else False'}