num_joints: 18 #including the hip root joint
fps: 30

multimodal_threshold: 0.5
dataset_type: FreeManDataset
dataset_name: freeman
precomputed_folder: "${dataset_precomputed_path}/FreeMan/${task.task_name}/"
annotations_folder: "${dataset_annotation_path}/FreeMan/${task.task_name}/"
dtype: float32

data_loader_train:
    stride: 10
    augmentation: 5
    shuffle: True
    actions: "all"
    da_mirroring: 0.5
    da_rotations: 1.0
    drop_last: True
    if_load_mmgt: False

data_loader_train_eval:
    stride: 30
    augmentation: 0
    shuffle: False
    actions: "all"
    da_mirroring: 0.
    da_rotations: 0.
    drop_last: False
    if_load_mmgt: False

data_loader_valid:
    stride: 30
    augmentation: 0
    shuffle: False
    segments_path: "${dataset.annotations_folder}/segments_valid.csv"
    actions: "all"
    drop_last: False
    if_load_mmgt: False
